# Confirm executable can be built on pushes to main branch
name: Main
run-name: build main branch
on:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
        run: git checkout HEAD
      - name: Download boost
        run: ./scripts/download_boost.sh
      - name: Preent directory
        run: echo ${PWD}
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build
      - name: Run executable
        run: cd build && ./LivingRooms